name: Lex1 Autorun

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  write-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Lex1"
          git config --global user.email "lex1-actions@furycom"

      - name: Create test file
        run: |
          echo "Test d’écriture par Lex1 - $(date)" > lex1_write_test.txt

      - name: Commit and push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          git add lex1_write_test.txt
          git commit -m "Lex1 test write file"
          git push origin main
