name: Lex1 Autorun

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Lex1 loop
        run: |
          python lex1_loop.py

      - name: Commit changes
        run: |
          git config user.email "lex1@furycom.org"
          git config user.name "Lex-1"
          git add data/yann.md
          git commit -m "Update yann.md" || echo "No changes to commit"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Push changes
        if: github.actor == 'Furycom'
        run: |
          git push origin main
